pankod/superplate-core-plugins

plugins/tailwind/extend.js
plugins/tailwind/package.json
plugins/tailwind/src/Components/Tailwind/index.tsx

add tailwind example 

---

plugins/sass/package.json
plugins/sass/src/Components/Sass/index.module.scss
plugins/sass/src/Components/Sass/index.tsx
prompt.json

Scss plugin

---

refine/plugins/i18n/src/components/header/index.tsx
refine/template/src/App.tsx

Update i18n Header

---

refine/plugins/custom-layout/src/components/sider/index.tsx
refine/plugins/less/src/styles/antd.less

remove buggy trigger styles

---

refine-nextjs/plugins/mui-example-pages/src/components/posts/list.tsx
refine-react/plugins/mui-example-pages/src/pages/posts/list.tsx

Added DeleteButton to Material UI examples.

fix: add delete button to mui examples

---

refine-react/template/src/index.tsx

fix: update render method accordingly to react 18

---

refine-react/plugins/auth-provider-google/extend.js
refine-react/plugins/auth-provider-google/package.json
refine-react/plugins/auth-provider-google/src/interfaces/google.d.ts
refine-react/plugins/auth-provider-google/src/pages/login.tsx
refine-react/plugins/auth-provider-google/src/utils/parse-jwt.ts
refine-react/template/public/index.html

We have updated our `Google auth provider` plugin with the new Google Identity Service.

fix: auth provider google plugin

---

refine-nextjs/plugins/antd-custom-layout/src/components/layout/sider/index.tsx
refine-nextjs/plugins/antd/package.json
refine-nextjs/plugins/mui-custom-layout/src/components/layout/sider/index.tsx
refine-nextjs/plugins/mui-example-pages/src/components/posts/create.tsx
refine-nextjs/plugins/mui-example-pages/src/components/posts/edit.tsx
refine-nextjs/plugins/mui/package.json
refine-react/plugins/antd-custom-layout/src/components/layout/sider/index.tsx
refine-react/plugins/antd/package.json
refine-react/plugins/mui-custom-layout/src/components/layout/sider/index.tsx
refine-react/plugins/mui-example-pages/src/pages/posts/create.tsx
refine-react/plugins/mui-example-pages/src/pages/posts/edit.tsx
refine-react/plugins/mui/package.json
refine-remix/plugins/antd-custom-layout/app/components/layout/sider/index.tsx
refine-remix/plugins/antd/package.json
refine-remix/plugins/mui-custom-layout/app/components/layout/sider/index.tsx
refine-remix/plugins/mui-example-pages/app/components/posts/create.tsx
refine-remix/plugins/mui-example-pages/app/components/posts/edit.tsx
refine-remix/plugins/mui/package.json

Updated custom sider component in `mui-custom-layout` and `antd-custom-layout` for **refine-react**, **refine-next** and **refine-remix** plugins.

feat: update custom layout/sider

---

refine-remix/plugins/mui/app/root.tsx

Added missed `React` import to **refine-remix**  plugins.

fix: missing import

---

refine-nextjs/plugins/mui-example-pages/src/components/posts/list.tsx
refine-react/plugins/mui-example-pages/src/pages/posts/list.tsx
refine-remix/plugins/mui-example-pages/app/components/posts/list.tsx

Added filter options for category and status columns.

fix(refine): update Material UI list pages

---

refine-nextjs/template/_package.json
refine-react/template/_package.json
refine-remix/template/_package.json

`refine CLI` added as a dependency

chore: add refine CLI as a dependency

---

refine-nextjs/template/_package.json

Updated `refine-nextjs` with `next@13`

feat: update `nextjs` to `v13`

---

refine-nextjs/plugins/antd-example-pages/pages/[[...refine]].tsx
refine-nextjs/plugins/chakra-example-pages/src/pages/[[...refine]].tsx
refine-nextjs/plugins/data-provider-strapi-v4/pages/[resource]/index.tsx
refine-nextjs/plugins/data-provider-strapi/pages/[resource]/index.tsx
refine-nextjs/plugins/i18n-chakra/src/components/layout/header/index.tsx
refine-nextjs/plugins/mantine-example-pages/pages/[[...refine]].tsx
refine-nextjs/plugins/mui-example-pages/pages/[[...refine]].tsx
refine-nextjs/template/pages/[[...refine]].tsx
refine-react/plugins/i18n-chakra/src/components/layout/header/index.tsx

Updated authentication logic in `refine-nextjs` template. Resolves https://github.com/refinedev/refine/issues/3259

fix(refine-nextjs): update authentication logic

---

refine-nextjs/template/next.config.js

issue : [#3578](https://github.com/refinedev/refine/issues/3578)

feat: add transpilePackages to nextjs with antd

---

refine-nextjs/plugins/antd/src/components/header/index.tsx
refine-nextjs/plugins/auth-provider-auth0/pages/_app.tsx
refine-nextjs/plugins/auth-provider-google/pages/_app.tsx
refine-nextjs/plugins/auth-provider-keycloak/pages/_app.tsx
refine-nextjs/plugins/i18n-antd/src/components/header/index.tsx

feat(refine-nextjs): add missing themed-layouts

---

refine-nextjs/plugins/antd/package.json
refine-nextjs/plugins/chakra/package.json
refine-nextjs/plugins/inferencer-headless/package.json
refine-nextjs/plugins/mantine/package.json
refine-nextjs/plugins/mui/package.json
refine-nextjs/template/_package.json
refine-react/plugins/antd/package.json
refine-react/plugins/chakra/package.json
refine-react/plugins/inferencer-headless/package.json
refine-react/plugins/mantine/package.json
refine-react/plugins/mui/package.json
refine-react/plugins/react-router-v6/package.json
refine-react/template/_package.json
refine-remix/plugins/antd/package.json
refine-remix/plugins/chakra/package.json
refine-remix/plugins/data-provider-appwrite/package.json
refine-remix/plugins/inferencer-headless/package.json
refine-remix/plugins/inferencer/package.json
refine-remix/plugins/mantine/package.json
refine-remix/plugins/mui/package.json
refine-remix/template/_package.json

packages list: https://www.npmjs.com/org/refinedev

chore: update refinedev package versions to latests

---

refine-nextjs/plugins/data-provider-appwrite/src/authProvider.ts
refine-nextjs/plugins/data-provider-strapi-v4/src/authProvider.ts
refine-react/plugins/auth-provider-auth0/extend.js
refine-react/plugins/auth-provider-google/extend.js
refine-react/plugins/auth-provider-keycloak/extend.js
refine-react/plugins/data-provider-appwrite/src/authProvider.ts
refine-react/plugins/data-provider-strapi-v4/src/authProvider.ts
refine-react/plugins/data-provider-supabase/src/authProvider.ts
refine-remix/plugins/auth-provider-custom/app/authProvider.ts
refine-remix/plugins/data-provider-appwrite/app/authProvider.ts
refine-remix/plugins/data-provider-strapi-v4/app/authProvider.ts
refine-remix/plugins/data-provider-supabase/app/authProvider.ts

Updated error values of `authProvider`s to show notification customization.

fix: update error values of `authProvider`s 

---

refine-nextjs/plugins/data-provider-strapi-v4/src/constants.ts
refine-react/plugins/data-provider-strapi-v4/src/constants.ts
refine-remix/plugins/data-provider-strapi-v4/app/constants.ts

The API URLs have been updated.

fix: update the strapi API URL

---

refine-nextjs/plugins/i18n-antd/next-i18next.config.js
refine-nextjs/plugins/i18n-chakra/next-i18next.config.js
refine-nextjs/plugins/i18n-mantine/next-i18next.config.js
refine-nextjs/plugins/i18n-mui/next-i18next.config.js
refine-nextjs/plugins/i18n/next-i18next.config.js

fix: i18n configuration

---

refine-nextjs/plugins/i18n-antd/next-i18next.config.js
refine-nextjs/plugins/i18n-chakra/next-i18next.config.js
refine-nextjs/plugins/i18n-mantine/next-i18next.config.js
refine-nextjs/plugins/i18n-mui/next-i18next.config.js
refine-nextjs/plugins/i18n/next-i18next.config.js

fix(refine-nextjs): update the `next.-i18next.config`

---

refine-nextjs/plugins/auth-provider-auth0/pages/login/index.tsx
refine-nextjs/plugins/auth-provider-google/pages/login/index.tsx
refine-nextjs/plugins/auth-provider-keycloak/pages/login/index.tsx
refine-nextjs/plugins/i18n-mui/src/components/header/index.tsx
refine-nextjs/plugins/mui/extend.js
refine-nextjs/plugins/mui/src/components/header/index.tsx
refine-nextjs/plugins/mui/src/contexts/index.tsx
refine-react/plugins/auth-provider-auth0/src/pages/login.tsx
refine-react/plugins/auth-provider-google/src/pages/login.tsx
refine-react/plugins/auth-provider-keycloak/src/pages/login.tsx
refine-react/plugins/i18n-mui/src/components/header/index.tsx
refine-react/plugins/mui/extend.js
refine-react/plugins/mui/src/components/header/index.tsx
refine-remix/plugins/auth-provider-auth0/app/routes/_auth.login.tsx
refine-remix/plugins/auth-provider-google/app/routes/_auth.login.tsx
refine-remix/plugins/auth-provider-keycloak/app/routes/_auth.login.tsx
refine-remix/plugins/mui/app/components/header/index.tsx
refine-remix/plugins/mui/app/contexts/ColorModeContext.tsx
refine-remix/plugins/mui/app/entry.client.tsx
refine-remix/plugins/mui/app/root.tsx
refine-remix/plugins/mui/extend.js

Replaced Material UI imports from barrel to subpath imports.

chore(material-ui): replace material ui imports

---

refine-nextjs/plugins/inferencer-headless/package.json
refine-nextjs/plugins/mui/package.json
refine-nextjs/template/_package.json
refine-react/plugins/inferencer-headless/package.json
refine-react/plugins/mui/package.json
refine-react/template/_package.json
refine-remix/plugins/inferencer-headless/package.json
refine-remix/plugins/mui/package.json
refine-remix/template/_package.json
refine-vite/plugins/inferencer-headless/package.json
refine-vite/plugins/mui/package.json
refine-vite/template/_package.json

Updated `@refinedev/mui`, `@refinedev/inferencer` versions and also the `@mui/x-data-grid` dependencies.
Waits https://github.com/refinedev/refine/pull/4454

chore(mui): upgrade mui deps

---

refine-nextjs/plugins/data-provider-appwrite/package.json
refine-nextjs/plugins/data-provider-appwrite/src/authProvider.ts
refine-react/plugins/data-provider-appwrite/package.json
refine-react/plugins/data-provider-appwrite/src/authProvider.ts
refine-remix/plugins/data-provider-appwrite/app/authProvider.ts
refine-remix/plugins/data-provider-appwrite/package.json
refine-vite/plugins/data-provider-appwrite/package.json
refine-vite/plugins/data-provider-appwrite/src/authProvider.ts

Added missing `register` method of `authProvider` to Appwrite data providers.

fix(appwrite): add missing `register` function

---

presets.js

chore: add Appwrite preset

---

refine-nextjs/template/Dockerfile
refine-remix/template/Dockerfile
refine-vite/template/Dockerfile

Added example Dockerfiles to `refine-nextjs`, `refine-remix` and `refine-vite` templates.

feat: add Dockerfile examples

---

refine-remix/plugins/antd-example/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-auth0/app/routes/_auth.tsx
refine-remix/plugins/auth-provider-auth0/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-auth0/app/routes/auth.auth0._index.tsx
refine-remix/plugins/auth-provider-auth0/app/routes/auth.auth0.callback.tsx
refine-remix/plugins/auth-provider-auth0/app/routes/auth.logout.tsx
refine-remix/plugins/auth-provider-auth0/extend.js
refine-remix/plugins/auth-provider-custom/app/routes/_auth.tsx
refine-remix/plugins/auth-provider-custom/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-google/app/routes/_auth.tsx
refine-remix/plugins/auth-provider-google/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-google/app/routes/auth.google._index.tsx
refine-remix/plugins/auth-provider-google/app/routes/auth.google.callback.tsx
refine-remix/plugins/auth-provider-google/app/routes/auth.logout.tsx
refine-remix/plugins/auth-provider-google/extend.js
refine-remix/plugins/auth-provider-keycloak/app/routes/_auth.tsx
refine-remix/plugins/auth-provider-keycloak/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-keycloak/app/routes/auth.keycloak._index.tsx
refine-remix/plugins/auth-provider-keycloak/app/routes/auth.keycloak.callback.tsx
refine-remix/plugins/auth-provider-keycloak/app/routes/auth.logout.tsx
refine-remix/plugins/auth-provider-keycloak/extend.js
refine-remix/plugins/data-provider-appwrite/app/routes/_auth.tsx
refine-remix/plugins/data-provider-appwrite/app/routes/_layout.tsx
refine-remix/plugins/data-provider-strapi-v4/app/routes/_auth.tsx
refine-remix/plugins/data-provider-strapi-v4/app/routes/_layout.tsx
refine-remix/plugins/data-provider-supabase/app/routes/_auth.tsx
refine-remix/plugins/data-provider-supabase/app/routes/_layout.tsx
refine-remix/plugins/headless-example/app/routes/_layout.tsx
refine-remix/plugins/mui-example/app/routes/_layout.tsx

Replaced removed `LoaderArgs` type from `@remix-run/node` with `LoaderFunctionArgs`.

fix(refine-remix): replace `LoaderArgs` with `LoaderFunctionArgs` type

---

refine-vite/plugins/auth-provider-keycloak/package.json

fix: update keycloak version
