pankod/superplate-core-plugins

react/plugins/redux/src/redux/slices/counter/index.spec.ts

Shows an error on the test file during the initial project running after successfully building with CLI using Redux as a plugin. 
To fix, I added a type parameter as shown on the error.
`TS2345: Argument of type '{}' is not assignable to parameter of type 'AnyAction'.
Property 'type' is missing in type '{}' but required in type 'AnyAction'.`

Fix redux counter test fail

---

refine-nextjs/plugins/custom-layout/src/components/layout/sider/index.tsx
refine-react/plugins/custom-layout/src/components/layout/sider/index.tsx

Replaced `useMenu` import in custom sider component with the one from `@pankod/refine-core`.
Waiting https://github.com/pankod/refine/pull/1952 and https://github.com/pankod/refine/pull/1985

refactor: replace `useMenu` import with `@pankod/refine-core`

---

refine-nextjs/plugins/i18n-antd/public/locales/de/common.json
refine-nextjs/plugins/i18n-antd/public/locales/en/common.json
refine-nextjs/plugins/i18n-mui/public/locales/de/common.json
refine-nextjs/plugins/i18n-mui/public/locales/en/common.json
refine-nextjs/plugins/i18n/public/locales/de/common.json
refine-nextjs/plugins/i18n/public/locales/en/common.json
refine-react/plugins/i18n-antd/public/locales/de/common.json
refine-react/plugins/i18n-antd/public/locales/en/common.json
refine-react/plugins/i18n-mui/public/locales/de.json
refine-react/plugins/i18n-mui/public/locales/en.json
refine-react/plugins/i18n/public/locales/de/common.json
refine-react/plugins/i18n/public/locales/en/common.json

added actions key for [`useBreadcrumb`](https://refine.dev/docs/core/hooks/useBreadcrumb/#translate) hook.
```
German
"actions": {
"list": "Aufführen",
"create": "Erstellen",
"edit": "Bearbeiten",
"show": "Zeigen"
},
English
"actions": {
"list": "List",
"create": "Create",
"edit": "Edit",
"show": "Show"
},
```

chore: add actions key to translation files

---

refine-nextjs/prompt.js
refine-react/prompt.js
refine-remix/plugins/chakra/app/root.tsx
refine-remix/prompt.js
refine-remix/template/.npmrc

Updated dark mode prompt order and moved above customization.
Resolves https://github.com/refinedev/refine/issues/3464

fix(refine): move dark mode prompts before customization

---

refine-nextjs/plugins/antd/extend.js
refine-nextjs/plugins/antd/src/components/header/index.tsx
refine-nextjs/plugins/antd/src/contexts/index.tsx
refine-nextjs/plugins/chakra/extend.js
refine-nextjs/plugins/chakra/src/components/header/index.tsx
refine-nextjs/plugins/i18n-antd/src/components/header/index.tsx
refine-nextjs/plugins/i18n-chakra/src/components/header/index.tsx
refine-nextjs/plugins/i18n-mantine/src/components/header/index.tsx
refine-nextjs/plugins/i18n-mui/src/components/header/index.tsx
refine-nextjs/plugins/mantine/extend.js
refine-nextjs/plugins/mantine/src/components/header/index.tsx
refine-nextjs/plugins/mui/extend.js
refine-nextjs/plugins/mui/src/components/header/index.tsx
refine-nextjs/plugins/mui/src/contexts/index.tsx
refine-nextjs/template/pages/_app.tsx

refine-nextjs:
-   [x] antd, i18n-antd:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] mui, 18n-mui:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] chakra-ui, i18n-chakra-ui:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] mantine, i18n-mantine:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.

feat(refine-nextjs): update layout to themed-layout

---

refine-react/plugins/antd/extend.js
refine-react/plugins/antd/src/components/header/index.tsx
refine-react/plugins/antd/src/contexts/color-mode/index.tsx
refine-react/plugins/auth-provider-google/package.json
refine-react/plugins/chakra/extend.js
refine-react/plugins/chakra/src/components/header/index.tsx
refine-react/plugins/chakra/src/components/index.ts
refine-react/plugins/i18n-antd/src/components/header/index.tsx
refine-react/plugins/i18n-chakra/src/components/header/index.tsx
refine-react/plugins/i18n-mantine/src/components/header/index.tsx
refine-react/plugins/i18n-mui/src/components/header/index.tsx
refine-react/plugins/mantine/extend.js
refine-react/plugins/mantine/src/components/header/index.tsx
refine-react/plugins/mui/extend.js
refine-react/plugins/mui/src/components/header/index.tsx
refine-react/plugins/mui/src/contexts/color-mode/index.tsx
refine-react/template/src/App.tsx

refine-react:
-   [x] antd, i18n-antd:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] mui, 18n-mui:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] chakra-ui, i18n-chakra-ui:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] mantine, i18n-mantine:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.

feat(refine-react): update layout to themed-layout

---

refine-remix/plugins/antd/app/components/header/index.tsx
refine-remix/plugins/antd/app/contexts/index.tsx
refine-remix/plugins/antd/extend.js
refine-remix/plugins/auth-provider-auth0/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-custom/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-google/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-keycloak/app/routes/_layout.tsx
refine-remix/plugins/chakra/app/components/header/index.tsx
refine-remix/plugins/chakra/app/root.tsx
refine-remix/plugins/data-provider-appwrite/app/routes/_layout.tsx
refine-remix/plugins/data-provider-strapi-v4/app/routes/_layout.tsx
refine-remix/plugins/data-provider-supabase/app/routes/_layout.tsx
refine-remix/plugins/inferencer/app/routes/_layout.tsx
refine-remix/plugins/mantine/app/components/header/index.tsx
refine-remix/plugins/mantine/app/root.tsx
refine-remix/plugins/mantine/extend.js
refine-remix/plugins/mui/app/components/header/index.tsx
refine-remix/plugins/mui/app/contexts/ClientStyleContext.ts
refine-remix/plugins/mui/app/contexts/ClientStyleContext.tsx
refine-remix/plugins/mui/app/contexts/ColorModeContext.tsx
refine-remix/plugins/mui/app/contexts/index.ts
refine-remix/plugins/mui/app/contexts/index.tsx
refine-remix/plugins/mui/app/entry.client.tsx
refine-remix/plugins/mui/extend.js

refine-remix:
-   [x] antd, i18n-antd:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] mui, 18n-mui:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] chakra-ui, i18n-chakra-ui:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.
-   [x] mantine, i18n-mantine:
-   [x] `<Layout>` updated to `<ThemedLayout>`.
-   [x] `<Header>` copied from `<ThemedHeader>`.

feat(refine-remix): add themed layout to auth provider pages

---

refine-nextjs/plugins/auth-provider-auth0/pages/_app.tsx
refine-nextjs/plugins/auth-provider-google/pages/_app.tsx
refine-nextjs/plugins/auth-provider-keycloak/pages/_app.tsx
refine-nextjs/template/pages/_app.tsx

Fixed: when headless selected `(ui-framework === "no")`. `<ThemedLayout>` should not exist.

fix(refine-nextjs): remove layout when headless selected

---

refine-nextjs/plugins/i18n-antd/src/components/header/index.tsx
refine-react/plugins/i18n-antd/src/components/header/index.tsx

Fixed deprecated `<Dropdown>` prop. To solve it,  used `menu` instead of deprecated `overlay`.

fix: use `menu`instead deprecated `overlay`

---

refine-vite/plugins/auth-provider-auth0/src/pages/login.tsx
refine-vite/plugins/auth-provider-google/src/pages/login.tsx
refine-vite/plugins/auth-provider-keycloak/src/pages/login.tsx
refine-vite/plugins/i18n-mui/src/components/header/index.tsx
refine-vite/plugins/mui/extend.js
refine-vite/plugins/mui/src/components/header/index.tsx

Updated imports for `@mui/material` and `@mui/icons-material` in `refine-vite` template.

chore(mui-vite): update imports

---

refine-nextjs/plugins/auth-provider-auth0/pages/_app.tsx
refine-nextjs/plugins/auth-provider-google/pages/_app.tsx
refine-nextjs/plugins/auth-provider-keycloak/pages/_app.tsx
refine-nextjs/template/pages/_app.tsx
refine-remix/plugins/auth-provider-auth0/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-custom/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-google/app/routes/_layout.tsx
refine-remix/plugins/auth-provider-keycloak/app/routes/_layout.tsx
refine-remix/plugins/data-provider-appwrite/app/routes/_layout.tsx
refine-remix/plugins/data-provider-strapi-v4/app/routes/_layout.tsx
refine-remix/plugins/data-provider-supabase/app/routes/_layout.tsx
refine-remix/plugins/inferencer/app/routes/_layout.tsx
refine-vite/template/src/App.tsx

This fixes the issue of icon and title not changing dynamically in refine's interactive templates. The provided `ThemedTitleV2` components were not used by the provided `ThemedSiderV2` since the props were not passed properly.

fix: missing title on customized siders

---

refine-nextjs/template/next.config.js

when next config has `transpilePackages`, npm run dev throws this error. to fix this we remove `transpilePackages`

fix(nextjs-antd): remove transpilePackages

---

refine-remix/plugins/chakra/app/entry.client.tsx

fixed : react-dom.development.js:86 Warning: ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

fix(remix-refine): deprecated hydrate error

---

refine-nextjs/plugins/antd/extend.js
refine-react/plugins/antd/extend.js
refine-remix/plugins/antd/extend.js
refine-vite/plugins/antd/extend.js

feat: Removed deprecated `@refinedev/antd notificationProvider` and added the new `@refinedev/antd useNotificationProvider`.

feat: use new antd notification provider

---

refine-nextjs/template/next.config.js

Remove `experimental.newNextLinkBehavior` since it's now the default and having this config causes a warning to shown on development server.

chore(refine-nextjs): remove redundant experimental config

---

refine-nextjs/template/next.config.js

To avoid ssr mismatches:
- add: @refinedev/nextjs-router to the next.config.js#transpilePackages
- https://github.com/refinedev/refine/issues/5197
- add: @refinedev/antd and refinedev/inferencer to the next.config.js#transpilePackages
- https://github.com/refinedev/refine/issues/4998
When antd is True:
- inferencer True, antd True, i18n True
```md 
module.exports = {
i18n,
transpilePackages: [
"@refinedev/nextjs-router", 
"@refinedev/antd",
"@refinedev/inferencer",
],
};
```
- inferencer False, antd True, i18n True
```md 
module.exports = {
i18n,
transpilePackages: [
"@refinedev/nextjs-router", 
"@refinedev/antd",
],
};
```
inferencer True, antd True, i18n False
```md 
module.exports = {
transpilePackages: [
"@refinedev/nextjs-router", 
"@refinedev/antd",
"@refinedev/inferencer",
],
}; …
```

feat: add transpile packages to nextjs

---

refine-nextjs/plugins/_base/src/components/menu/index.tsx
refine-nextjs/plugins/auth-provider-auth0/pages/_app.tsx
refine-nextjs/plugins/auth-provider-google/pages/_app.tsx
refine-nextjs/plugins/auth-provider-keycloak/pages/_app.tsx
refine-nextjs/template/pages/_app.tsx
refine-react/plugins/_base/src/components/menu/index.tsx
refine-react/template/public/index.html
refine-react/template/src/App.tsx
refine-remix/plugins/_base/app/components/menu/index.tsx
refine-remix/plugins/chakra/app/root.tsx
refine-remix/plugins/mantine/app/root.tsx
refine-remix/plugins/mui/app/root.tsx
refine-remix/template/app/root.tsx
refine-vite/plugins/_base/src/components/menu/index.tsx
refine-vite/template/index.html
refine-vite/template/src/App.tsx

Added `useNewQueryKeys: true` to the `<Refine>` component options to enable new structure for the query keys by default.
Also added missing `projectId` property to some templates.

chore(refine): add `useNewQueryKeys: true` to options

---

refine-nextjs/plugins/data-provider-airtable/src/providers/data-provider/index.ts
refine-remix/plugins/data-provider-airtable/extend.js
refine-vite/plugins/data-provider-airtable/extend.js

Airtable's API key is deprecated https://support.airtable.com/docs/airtable-api-key-deprecation-notice. Personel Access Token used instead of API key.

feat(data-provider-airtable): update api token

---

refine-nextjs/template/.dockerignore
refine-nextjs/template/next.config.mjs

Fixes https://github.com/refinedev/refine/issues/6540

feat: add output standalone and .dockerignore

---

refine-nextjs/plugins/antd/package.json
refine-vite/plugins/antd/package.json

Depends on https://github.com/refinedev/refine/pull/6369
Updates the `@refinedev/antd` version to the next minor and updates `antd` and `@ant-design/icons` versions to the latest ranges.

chore(antd): bump antd package versions
